### ISSUE TITLE
[FEATURE] 能在配置文件中添加字体字段吗？

### ISSUE THREAD

**Issue by userxiaosi** [Lruihao/FixIt#158]
### Describe the feature you want 描述你的功能需求

能在配置文件中添加字体字段吗？默认字体I与L辨识度不高，希望能在配置文件中增加相关选项

**Comment by userxiaosi** [comment]
纠正，是大写i与小写L辨识度不高

**Comment by Lruihao** [comment]
@userxiaosi 你可以将 [_custom.scss](https://github.com/Lruihao/FixIt/blob/master/assets/css/_custom.scss) 复制到自己博客相似相同目录，在 _custom.scss 里你可以自定义任何的 CSS 样式，比如全局修改字体你可以这样写

```css
html {
  font-family: 'system-ui, -apple-system'
}
```
