### ISSUE TITLE
[BUG] Post中作者头像图片失效问题

### ISSUE THREAD

**Issue by homeproject7** [Lruihao/FixIt#313]
### Describe the bug 描述你遇到的错误

Fix theme 升级之后，
作者头像图片采用本地avatar.png
在主页上，post预览条目中作者头像图片能正常显示；
但进入post之后，作者头像图片即无法显示，查看element，可以看到图片链接有问题。
格式为 "http://url/posts/post_name/images/avatar.png"，显然路径出错了。
用了线上的gavatar，这个问题容易被忽略

**Comment by Lruihao** [comment]
配置文件填的什么




李瑞豪
***@***.***




------------------ 原始邮件 ------------------
发件人: 家园工程 HomeProject ***@***.***&gt;
发送时间: 2023年3月30日 20:16
收件人: hugo-fixit/FixIt ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [hugo-fixit/FixIt] [BUG] Post中作者头像图片失效问题 (Issue #313)





 
Describe the bug 描述你遇到的错误
 
Fix theme 升级之后，
 作者头像图片采用本地avatar.png
 在主页上，post预览条目中作者头像图片能正常显示；
 但进入post之后，作者头像图片即无法显示，查看element，可以看到图片链接有问题。
 格式为 "http://url/posts/post_name/images/avatar.png"，显然路径出错了。
 用了线上的gavatar，这个问题容易被忽略
 
Expected behavior 期待的行为
 
No response
 
Screenshots 屏幕截图
 
No response
 
Build Environment 构建环境
 
No response
 
Preview Environment 预览环境
 
No response
 
Additional Information 补充信息
 
No response

**Comment by homeproject7** [comment]
params.toml
``` toml
# Home page config
[home]
  # FixIt 0.2.0 | NEW amount of RSS pages
  rss = 10
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    # home profile Avatar image 标记
    avatarURL = "images/avatar.png"
    # FixIt 0.2.17 | NEW identifier of avatar menu link
    avatarMenu = "about"
    # FixIt 0.2.7 | CHANGED title shown in home page (HTML format is supported)
    title = "家园工程 Home Project"
    # subtitle shown in home page
    subtitle = "变得更好"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # FixIt 0.2.0 | NEW disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
```
``` toml
[gravatar]
  # FixIt 0.2.18 | NEW Depends on the author's email, if the author's email is not set, the local avatar will be used
  # set false，using local avatar
  enable = false
  # Gravatar host, default: "www.gravatar.com"
  host = "gravatar.loli.net" # ["cn.gravatar.com", "gravatar.loli.net", ...]
  style = "" # ["", "mp", "identicon", "monsterid", "wavatar", "retro", "blank", "robohash"]
```
author.toml
```toml
name = "家园工程"
email = "homeporject@gmail.com"
link = "https://github.com/homeproject7"

avatar = "images/avatar.png"
```
