### ISSUE TITLE
enhance highlight feature

### ISSUE THREAD

**Issue by Lruihao** [Lruihao/FixIt#43]
为了更好的适配主题的 `dark/light` 样式设计，以下必要设置请保持和主题文档一致，尤其是 `markup.highlight.noClasses=false`
```toml
[markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    # ...
```

`markup.highlight.noClasses=false`，意味着 `markup.highlight.style` 参数失效，若想自定义 hightlight style 可替换掉 `_variables.scss` 中的相关颜色变量值

**Comment by Lruihao** [comment]
- https://gohugo.io/content-management/syntax-highlighting
- https://github.com/dillonzq/LoveIt/issues/158
- https://swapoff.org/chroma/playground/

**Comment by Lruihao** [comment]
为了更好的完成主题的样式设计，FixIt 将占用 Hugo 的一些系统设置，如下必要设置请保持和主题一致
```toml
[markup.highlight]
  noClasses = false # whether to use classes instead of inline styles
  lineNumbersInTable = true # whether to show line numbers in tables
  # ...
```
